M48
; DRILL file KiCad 10.0.1 date 2026-09-27T15:05:58
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-09-27T15:05:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1457
%
G90
G05
T1
X5.7739Y-3.107
X6.0015Y-3.107
T2
X6.1838Y-4.5695
T3
X5.3964Y-4.5695
T4
X5.9479Y-3.7731
M30
